### ISSUE TITLE
Incorrect Enum values

### ISSUE THREAD

**Issue by Hugoz** [nium-global/nium-openapi#5]
Some Enums values are incorrect in `nium.yaml`. The description is correct, but the values are not. 

Example:
```
 settlementStatus:
          description:
            "This field contains the settlement status.This field can take\
            \ the following values:\nUnsettled\nSettled\n Released\nDisputed\nDisputeClosed\n\
            Waived"
          enum:
            - APPROVED
            - DECLINED
            - BLOCKED
            - SETTLED
            - UNSETTLED
            - REVERSAL
            - RELEASED
            - PENDING
            - WAIVED
            - DISPUTED
            - DISPUTE_CLOSED
            - IN_PROGRESS
            - REJECTED
            - RETURNED
            - AWAITING_FUNDS
            - EXPIRED
            - CANCELLED
            - SCHEDULED
            - NA
          type: string
```

It should be:
```
 settlementStatus:
          description:
            "This field contains the settlement status.This field can take\
            \ the following values:\nUnsettled\nSettled\n Released\nDisputed\nDisputeClosed\n\
            Waived"
          enum:
            - Unsettled
            - Settled
            - Released
            - Disputed
            - DisputeClosed
            - Waived
          type: string
```

This applies to a few Enum values for a few endpoints. For example `status`, `settlementStatus` and `complianceStatus` in `WalletTransactionResponseDTO`.
